Repository open-services-group/community, pull requests merged in 2022-05, with the labels that each got.

#121 feat(sig-services): Add secure data handling requirement
  sig-services/service-requirements/secure-user-data-handling.md
Labels: size/S, lgtm, approved

#168 Create testing.md
  sig-services/service-requirements/testing.md
Labels: approved, size/M

#179 Add an 'epic' label
  labels.md
  labels.yaml
Labels: lgtm, approved, size/XS

#180 feat: Add peribolos kind/* labels for CI
  labels.md
  labels.yaml
Labels: size/S, lgtm, approved
