Repository open-services-group/community, pull requests merged in 2022-07, with the labels that each got.

#240 Remove a few broken links
  sig-wg-lifecycle.md
Labels: lgtm, approved, size/XS

#235 Add VannTen (Max Gautier) as project member
  github-config.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#245 feat(sig-services): Add code of conduct guideline
  sig-services/service-requirements/code-of-conduct.md
Labels: size/S, lgtm, approved

#210 feat(sig-services): add security implications requirement
  sig-services/service-requirements/security-implications.md
Labels: size/S, lgtm, approved
