Repository open-services-group/community, pull requests merged in 2022-02, with the labels that each got.

#30 Add sig services
  OWNERS_ALIASES
  liaisons.md
  sig-list.md
  sig-services/OWNERS
  sig-services/README.md
  sig-services/charter.md
  sigs.yaml
Labels: lgtm, approved, size/L

#36 add os-climate subproject to sig-data-science
  sig-data-science/README.md
  sigs.yaml
Labels: lgtm, approved, size/M

#39 Add sub-project metrics repo
  github-config.yaml
Labels: approved, size/XS

#40 Add maintainers for metrics sub project
  github-config.yaml
Labels: size/S

#41 https added to meet.google links
  sig-data-science/README.md
  sig-list.md
  sigs.yaml
Labels: size/S, lgtm, approved

#44 Revert creation of metrics team
  github-config.yaml
Labels: size/S, approved

#45 Create the metrics team
  github-config.yaml
Labels: size/S

#49 Add metrics maintainers team
  github-config.yaml
Labels: lgtm, approved, size/XS

#50 Add Oindrilla to leader of byon/build-pipelines
  OWNERS_ALIASES
  sig-list.md
  sigs.yaml
  wg-byon-build-pipelines/README.md
Labels: size/S, lgtm, approved

#52 Add Shrey to SIG Services leads
  OWNERS_ALIASES
  sig-list.md
  sig-services/README.md
  sigs.yaml
Labels: lgtm, approved, size/XS

#54 Add Samuel to OSG community
  github-config.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#55 Small fix to readme
  sig-data-science/README.md
Labels: lgtm, approved, size/XS

#57 Fix a couple of recent changes
  sig-list.md
  sigs.yaml
Labels: lgtm, approved, size/XS

#34 create-SIG-community-experience
  OWNERS_ALIASES
  liaisons.md
  sig-community-experience/OWNERS
  sig-community-experience/README.md
  sig-community-experience/charter.md
  sig-list.md
  sigs.yaml
Labels: approved, size/L

#46 add ADR wrt OWNERS file
  .pre-commit-config.yaml
  adr/0000-use-OWNERS-rather-than-github-teams.md
  adr/template.md
Labels: kind/feature, lgtm, approved, size/L

#68 Added details to WG BYON Readme
  sigs.yaml
  wg-byon-build-pipelines/README.md
Labels: lgtm, approved, size/XS

#70 Add shreekarSS to OSG community
  github-config.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#80 feat(sig-services): Introduce Peribolos as a service
  github-config.yaml
  sig-services/README.md
  sigs.yaml
Labels: approved, size/M

#83 :exclamation: Peribolos binaries is shifted to /ko-app/ dir
  .prow.yaml
Labels: approved, size/XS
