Repository open-services-group/community, pull requests merged in 2022-03, with the labels that each got.

#84 Update label_sync binary path
  .prow.yaml
Labels: lgtm, approved, size/XS

#82 feat(org-gov): Share documentation on how to create a new subproject
  generator/sig_readme.tmpl
  sig-community-experience/README.md
  sig-data-science/README.md
  sig-data-science/how-to-create-a-subproject.md
  sig-data-science/subproject-lifecycle.md
  sig-services/README.md
  subproject-lifecycle.md
Labels: lgtm, approved, size/L

#86 Added oindrillac to byon maintainers
  github-config.yaml
Labels: approved, size/XS

#95 feat(sig-services): Add peribolos-as-a-service mtg
  sig-list.md
  sig-services/README.md
  sigs.yaml
Labels: size/S, lgtm, approved

#90 Add missing labels for SIGs and Working Groups
  labels.md
  labels.md.tmpl
  labels.yaml
Labels: lgtm, approved, size/L

#94 Improvements to subproject lifecycle doc
  subproject-lifecycle.md
Labels: size/S, lgtm, approved

#100 Add Tom and Shrey to org admin
  github-config.yaml
Labels: approved, size/XS

#101 adding gregory to open-services-group
  github-config.yaml
Labels: lgtm, needs-ok-to-test, approved, size/XS

#102 feat(sig-services): Add guideline template
  sig-services/service-requirements/.template.md
Labels: size/S, lgtm, approved

#104 add aakankshaduggal to AIOps team
  github-config.yaml
Labels: lgtm, approved, size/XS
