Repository open-services-group/community, pull requests merged in 2022-04, with the labels that each got.

#103 feat(sig-services): add contract-duration requirement
  sig-services/service-requirements/contract-duration.md
Labels: size/S, approved, sig/services

#114 Create meeting-template.md
  sig-community-experience/meeting-template.md
Labels: lgtm, approved, size/M

#105 feat(sig-services): Create add or remove user requirement
  sig-services/service-requirements/add-or-remove-user.md
Labels: size/S, lgtm, approved

#116 Update OWNERS file url format.
  sigs.yaml
Labels: approved, size/XS

#120 feat(sig-services): Create rbac-policy.md in sig services requirements
  sig-services/service-requirements/rbac-policy.md
Labels: size/S, approved

#132 Add dmick to osg org members
  github-config.yaml
Labels: approved, size/XS

#139 adding schwesig to Steering:
  github-config.yaml
Labels: approved, size/XS

#124 First draft of device failure prediction WG charter
  OWNERS_ALIASES
  github-config.yaml
  sigs.yaml
  wg-device-failure-prediction/OWNERS
  wg-device-failure-prediction/charter.md
Labels: approved, size/M, ok-to-test

#119 wg byon charter update
  .pre-commit-config.yaml
  OWNERS_ALIASES
  sig-list.md
  sigs.yaml
  wg-byon-build-pipelines/README.md
  wg-byon-build-pipelines/charter.md
Labels: size/S, lgtm, approved

#142 Added issue template
  .github/ISSUE_TEMPLATE/user_story_issue.md
Labels: size/S, lgtm, approved
