Repository open-services-group/community, pull requests merged in 2022-06, with the labels that each got.

#212 feat: Create probot-extensions repo
  github-config.yaml
Labels: approved, size/XS

#218 sigs.yaml - update meeting times for SIG ComExp
  OWNERS_ALIASES
  sig-community-experience/README.md
  sig-list.md
  sigs.yaml
  wg-device-failure-prediction/README.md
Labels: lgtm, approved, size/L

#219 sigs.yaml - replace non working OWNERS link
  sigs.yaml
Labels: kind/bug, lgtm, size/XS, priority/important-soon, sig/community-experience, area/governance

#220 auto update readme.md
  sig-community-experience/README.md
Labels: lgtm, approved, size/XS

#221 feat: Add probot-template repo
  github-config.yaml
Labels: lgtm, approved, size/XS

#232 feat: Relocate Probot repositories to Operate First
  github-config.yaml
  labels.md
  labels.yaml
Labels: approved, size/M
