Repository open-services-group/community, pull requests merged in 2022-01, with the labels that each got.

#10 add WG label for BYON
  .pre-commit-config.yaml
  labels.yaml
  wg-byon-build-pipelines/OWNERS
Labels: size/S, lgtm, approved

#11 remove unused wg-odhDevSecOps
  wg-odhDevSecOps/README.md
Labels: approved, size/XS

#5 WIP: Wg devsecops
  OWNERS_ALIASES
  sigs.yaml
  wg-devsecops/OWNERS
  wg-devsecops/README.md
  wg-devsecops/charter.md
Labels: approved, size/M

#12 cleanup links to slack channels
  generator/list.tmpl
  generator/sig_readme.tmpl
  generator/ug_readme.tmpl
  sig-data-science/README.md
  sig-list.md
  sig-wg-lifecycle.md
Labels: size/S, approved

#14 Add wg devsecops repo.
  github-config.yaml
Labels: size/S

#15 remove folder sig, following Kubernetes Community
  sig/README.md
  sig/charter.md
  sig/sig-charter-template.md
  sig/sig-devSecOps/README.md
  sig/sig-governance-requirements.md
  sig/sig-governance.md
  sig/sig-observability/README.md
  sig/sig-productManagement/README.md
  sig/sig-reproducibility/README.md
  sig/sig-userExperience/README.md
  sig/sig-velocity/README.md
Labels: approved, size/M

#17 updated ds-sig meet time and chair
  sigs.yaml
Labels: size/S, approved

#19 fix: Update steering committee
  OWNERS_ALIASES
  committee-steering/README.md
  liaisons.md
  sig-data-science/README.md
  sig-list.md
  sigs.yaml
Labels: size/S, lgtm, approved

#21 chore: Set approvers to committee-steering
  OWNERS
Labels: approved, size/XS

#18 Update sig-list link
  README.md
Labels: lgtm, approved, size/XS

#13 prefix url with scheme
  sigs.yaml
Labels: approved, size/XS

#24 add google doc as SIG meeting archive
  sigs.yaml
Labels: lgtm, approved, size/XS

#25 Add operate first data science community subproject
  sig-data-science/README.md
  sigs.yaml
Labels: size/S, lgtm, approved

#28 updated charter language after SIG meeting 01-19-22
  sig-data-science/charter.md
Labels: lgtm, approved, size/XS

#23 add agenda doc for steering committee
  sigs.yaml
Labels: lgtm, approved, size/XS

#29 chore: Generate
  committee-steering/README.md
  sig-data-science/README.md
  sig-list.md
  sigs.yaml
  wg-byon-build-pipelines/README.md
  wg-devsecops/README.md
Labels: size/S, approved

#31 add how-to-create-a-subproject.md for sig-data-science
  sig-data-science/how-to-create-a-subproject.md
Labels: lgtm, approved, size/M
